AvaliacaoSemanal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^avaliacao/', include('avaliacao.urls')),
    # url(r'^dashboard/', include('dashboard.urls')),
]

avaliacao/urls.py
from django.conf.urls import url
from . import views

app_name='avaliacao'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^questionario/(?P<avaliacao_id>\d+)?', views.questionario, name='questionario'),
	url(r'^questionario/(?P<avaliacao_id>\d+)?/(?P<questao_id>\d+)?/', views.questionario, name='questionario'),
	# url(r'^questionario/', views.questionario, name='questionario'),
]

avaliacao/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.
class Usuario(models.Model):
	FUNCAO = {
		('O','Operador'),
		('A','Administrador')
	}
	user = models.OneToOneField(User)
	nome = models.CharField(max_length=50, null=False)
	nome_usuario = models.CharField(max_length=25, null=False)
	funcao = models.CharField(max_length=1, choices=FUNCAO)
	status = models.BooleanField(default=True)

	def __str__(self):
		return self.nome

class Questao(models.Model):
	enunciado = models.TextField(null=False)

	def __str__(self):
		return self.enunciado

class Avaliacao(models.Model):
	periodo_inicio = models.DateField(null=False)
	periodo_fim = models.DateField(null=False)
	criado_em = models.DateTimeField(auto_now_add = True)
	questoes = models.ManyToManyField(Questao)

	# def __str__(self):
	# 	return self.periodo_inicio.strftime('%m/%d/%Y')
		# return 'De: ' + '{:%m/%d/%Y}'.format(self.periodo_inicio) + ' a ' + '{:%m/%d/%Y}'.format(self.periodo_fim)

class Resposta(models.Model):
	valor = models.IntegerField(null=False)
	criado_em = models.DateTimeField(auto_now_add=True)
	atualizado_em = models.DateTimeField(auto_now_add=True)
	usuario = models.ForeignKey(Usuario, on_delete = models.CASCADE, related_name = 'usuarios')
	avaliacao = models.ForeignKey(Avaliacao, on_delete = models.CASCADE, related_name= 'avaliacoes')
	questao = models.ForeignKey(Questao, on_delete= models.CASCADE, related_name = "questoes")
	criado_em = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return 'Usuario: ' + self.usuario + ', Avaliacao: ' + self.avaliacao + ', Resposta: ' + self.valor
		return self.valor

dashboard/models.py
from django.db import models

# Create your models here.

avaliacao/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import date
from .models import *

# Create your views here.
def index(request):
	return render(request, 'index.html');

def questionario(request, avaliacao_id=False, questao_id=False):
	avaliacoes = Avaliacao.objects.all();
	# Caso id da avaliacao nao tenha sido especificado, pegar a avaliacao da semana corrente
	if not avaliacao_id:
		avaliacao_selecioanda = Avaliacao.objects.filter(periodo_inicio__lte=date.today(), periodo_fim__gte=date.today())[:1].get()
	else:
		avaliacao_selecioanda = Avaliacao.objects.get(id=avaliacao_id)

	if not questao_id:
		questao = avaliacao_selecioanda.questoes.all()[0]
	else :
		questao = avaliacao_selecioanda.questoes.get(id=questao_id)

	usuarios = Usuario.objects.filter(funcao__in=('O'))

	qnt_questoes = avaliacao_selecioanda.questoes.count()
	respostas = 0
	percentagem = (respostas / qnt_questoes) * 100;

	return render(request, 'questionario.html',
		{'avaliacoes': avaliacoes, 
		'avaliacao_selecioanda': avaliacao_selecioanda, 
		'questao': questao,
		'usuarios': usuarios,
		'qnt_questoes': qnt_questoes,
		'respostas': respostas,
		'percentagem': percentagem}
	);

dashboard/views.py
from django.shortcuts import render

# Create your views here.

avaliacao/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="Deyvid Yury">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.js' %}"></script>
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'avaliacao:index' %}">Avaliação Semanal</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'avaliacao:index' %}">Home</a></li>
            <li><a href="{% url 'avaliacao:questionario' %}">Questionario</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      {% block content %} {% endblock %}
      

    </div> <!-- /container -->

    
    <footer class="footer">
      <div class="container">
        <p class="text-muted text-center">&copy; 2017 - Deyvid Yury</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
  </body>
</html>

avaliacao/templates/index.html
{% extends 'base.html' %}

{% block content %}
<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron">
	<h1 class="text-center">Avaliação Semanal</h1>
	<p class="text-center">
		Ajude-nos a melhorar nossos processos.
	</p>
	<p class="text-center">
		<a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">Entrar</a>
	</p>
</div>
{% endblock %}

avaliacao/templates/questionario.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
	<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-3 col-md-offset-4 form-group ">
		<label class="text-center" for="">Avaliações</label>
		<select name="avaliacao" id="avaliacao_select" class="form-control text-center">
			{% for avaliacao in avaliacoes %}
				<option value="{{avaliacao.id}}" {% if avaliacao.id == avaliacao_selecioanda.id %} selected {% endif %}>{{ avaliacao.periodo_inicio }} a {{ avaliacao.periodo_fim }}</option>
			{% endfor %}
		</select>
	</div>

	<div class="col-xs-12">
		<h3>{{ questao.enunciado }}</h3>
		<form action="{% url 'avaliacao:questionario' %}" method="post" class="form-inline">
			<table class="table">
				<tbody>
				{% for usuario in usuarios %}
					<tr>
						<td>{{ usuario.nome }}</td>
						<td>
							<label for="" class="radio-inline">
								<input type="radio" name="resposta_usuario_{{usuario.id}}" required> 6
							</label>
							<label for="" class="radio-inline">
								<input type="radio" name="resposta_usuario_{{usuario.id}}" required> 7
							</label>
							<label for="" class="radio-inline">
								<input type="radio" name="resposta_usuario_{{usuario.id}}" required> 8
							</label>
							<label for="" class="radio-inline">
								<input type="radio" name="resposta_usuario_{{usuario.id}}" required> 9
							</label>
							<label for="" class="radio-inline">
								<input type="radio" name="resposta_usuario_{{usuario.id}}" required> 10
							</label>
						</td>
					</tr>
				{% empty %}
					<p>Nenhum usuario cadastrado ainda.</p>
				{% endfor %}
				</tbody>
			</table>
			<button type="submit" class="btn btn-primary center-block">Salvar</button>
		</form>

		<br>

		<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-3 col-md-offset-4">
			<div class="progress">
			  <div class="progress-bar" role="progressbar" aria-valuenow="{{ percentagem }}" aria-valuemin="0" aria-valuemax="5" style="width: {{percentagem}}%;">
			    {{percentagem | floatformat:1}}%
			  </div>
			</div>
			<div class="btn-group btn-group-justified" role="group" aria-label="...">
			  <div class="btn-group" role="group">
			    <button type="button" class="btn btn-default">Anterior</button>
			  </div>
			  <div class="btn-group" role="group">
			    <button type="button" class="btn btn-default">Próxima</button>
			  </div>
			</div>
		</div>
	</div>
</div>

<script>
$(document).ready(function(){
	$('#avaliacao_select').change(function(){
		var id = $(this).val();
		var url = '{% url "avaliacao:questionario" avaliacao_id='id' %}';
		url = url.replace('id',id);
		console.log(url);
		window.location.href = url;
	})
})
</script>

{% endblock %}